name: cam_bus
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_fonts: ^4.0.4
  flutter_native_splash: ^2.2.19
  get: ^4.6.5
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#f7f6f1"
  image: assets/images/cambus-logo.jpg
  color_dark: "#272727"
  image_dark: assets/images/cambus-logo.jpg

  android_12:
    image: assets/images/cambus-logo.jpg
    icon_background_color: "#f7f6f1"
    image_dark: assets/images/cambus-logo.jpg
    icon_background_color_dark: "#272727"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/onboarding_images/
    - assets/images/welcome_images/
